services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: hotel_sqlserver
    environment:
      ACCEPT_EULA: "1"
      MSSQL_SA_PASSWORD: "YourStrong@Passw0rd"
    ports:
      - "1434:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  sqlserver_data: